version: '3.8'
services:
  airflow-scheduler:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/airflow:latest
    command:
     - scheduler
    user: '50000:0'
    environment:
      AIRFLOW__CELERY__BROKER_URL: redis://:6a79a8a6664ef4f874027693540ec231@redis:6379/0
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    networks:
     - apperture_net
    dns: 8.8.8.8
    secrets:
     -
      source: airflow.env
      target: /opt/airflow/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-prod-log-group
        awslogs-region: ap-south-1
        awslogs-stream: airflow-scheduler
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.hostname == worker4
      resources:
        reservations:
          cpus: '0.4'
          memory: 400M
        limits:
          cpus: '0.7'
          memory: 650M
  airflow-triggerer:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/airflow:latest
    command:
     - triggerer
    user: '50000:0'
    environment:
      AIRFLOW__CELERY__BROKER_URL: redis://:6a79a8a6664ef4f874027693540ec231@redis:6379/0
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    networks:
     - apperture_net
    dns: 8.8.8.8
    secrets:
     -
      source: airflow.env
      target: /opt/airflow/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-prod-log-group
        awslogs-region: ap-south-1
        awslogs-stream: airflow-triggerer
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.hostname == worker4
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.5'
          memory: 512M
  airflow-webserver:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/airflow:latest
    command:
     - webserver
    user: '50000:0'
    environment:
      AIRFLOW__CELERY__BROKER_URL: redis://:6a79a8a6664ef4f874027693540ec231@redis:6379/0
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    ports:
     - 8080:8080
    networks:
     - apperture_net
     - traefik-public
    dns: 8.8.8.8
    secrets:
     -
      source: airflow.env
      target: /opt/airflow/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-prod-log-group
        awslogs-region: ap-south-1
        awslogs-stream: airflow-webserver
    deploy:
      labels:
        traefik.http.routers.airflow-webserver-http.middlewares: https-redirect
        traefik.http.routers.airflow-webserver-http.entrypoints: http
        traefik.http.routers.airflow-webserver-https.tls: 'true'
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.routers.airflow-webserver-https.rule: Host(`airflow.apperture.io`)
        traefik.http.routers.airflow-webserver-http.rule: Host(`airflow.apperture.io`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.airflow-webserver-https.entrypoints: https
        traefik.http.services.airflow-webserver.loadbalancer.server.port: '8080'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.airflow-webserver-https.tls.certresolver: le
      placement:
        constraints:
         - node.hostname == worker4
  airflow-worker:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/airflow:latest
    command:
     - celery
     - worker
    user: '50000:0'
    environment:
      AIRFLOW__CELERY__BROKER_URL: redis://:6a79a8a6664ef4f874027693540ec231@redis:6379/0
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      DUMB_INIT_SETSID: '0'
    networks:
     - apperture_net
    dns: 8.8.8.8
    secrets:
     -
      source: airflow.env
      target: /opt/airflow/.env
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.hostname == worker4
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_USER: airflow
    ports:
     - 5432:5432
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
     - apperture_net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.hostname == worker4
networks:
  apperture_net:
    external: true
  traefik-public:
    external: true
volumes:
  postgres_data:
    external: true
secrets:
  airflow.env:
    external: true
