version: '3.7'
services:
  alertmanager:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/alertmanager:latest
    networks:
     - net
     - swarmpit_net
    secrets:
     -
      source: alertmanager.env
      target: /code/.env
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.3'
          memory: 124M
        limits:
          cpus: '0.5'
          memory: 256M
  backend:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
    networks:
     - net
     - traefik-public
    secrets:
     -
      source: backend.env
      target: /code/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: backend
    deploy:
      labels:
        traefik.http.routers.backend-https.service: backend
        traefik.http.routers.backend-docs.rule: Host(`api.staging.apperture.io`) &&
          PathPrefix(`/docs`, `/openapi.json`, `/redoc`)
        traefik.http.routers.backend-http.service: backend
        traefik.http.routers.backend-docs.tls: 'true'
        traefik.http.routers.backend-http.rule: Host(`api.staging.apperture.io`)
        traefik.http.middlewares.docs-auth.basicauth.users: <username>:<aprhashedpassword>
        traefik.http.routers.backend-https.tls.certresolver: le
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.routers.backend-http.entrypoints: http
        traefik.http.routers.backend-https.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.backend-docs.entrypoints: https
        traefik.http.routers.backend-docs.tls.certresolver: le
        traefik.http.routers.backend-docs.service: backend-docs
        traefik.http.services.backend.loadbalancer.server.port: '8001'
        traefik.http.services.backend-docs.loadbalancer.server.port: '8001'
        traefik.http.routers.backend-https.tls: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.backend-https.rule: Host(`api.staging.apperture.io`)
        traefik.http.routers.backend-http.middlewares: https-redirect
        traefik.http.routers.backend-docs.middlewares: docs-auth
      update_config:
        delay: 5s
        order: start-first
      placement:
        constraints:
         - node.role != manager
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1.0'
          memory: 2048M
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
     - 8123:8123
     - 9000:9000
    volumes:
     - /ch/data:/var/lib/clickhouse/
     - /ch/logs:/var/log/clickhouse-server/
     - /ch/config.d:/etc/clickhouse-server/config.d/
     - /ch/backups:/backups
    networks:
     - net
     - traefik-public
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.hostname == worker3ch
  data_processor:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/data_processor:latest
    networks:
     - net
    secrets:
     -
      source: data_processor1.env
      target: /code/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: dataprocessor
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      placement:
        constraints:
         - node.hostname == worker2
      resources:
        reservations:
          memory: 1000M
        limits:
          memory: 7800M
  events_producer:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/events_producer:latest
    networks:
     - net
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: events_producer
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1.0'
          memory: 2048M
  events_consumer:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/events_consumer:latest
    secrets:
     -
      source: events_consumer.env
      target: /code/.env
    networks:
     - net
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: events_consumer
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1.0'
          memory: 2048M
  frontend:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/frontend:88358f6
    networks:
     - net
     - traefik-public
    secrets:
     -
      source: frontend.env
      target: /code/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: frontend
    deploy:
      labels:
        traefik.http.routers.frontend-https.rule: Host(`app.staging.apperture.io`)
        traefik.http.routers.frontend-https.entrypoints: https
        traefik.http.routers.frontend-https.tls.certresolver: le
        traefik.http.routers.frontend-http.middlewares: https-redirect
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.routers.frontend-http.rule: Host(`app.staging.apperture.io`)
        traefik.http.routers.frontend-https.tls: 'true'
        traefik.http.services.frontend.loadbalancer.server.port: '3000'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.frontend-http.entrypoints: http
      placement:
        constraints:
         - node.hostname == worker1
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.5'
          memory: 512M
  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: <redispassword>
    ports:
     - 6379:6379
    volumes:
     - apperture_redisdata:/bitnami/redis/data
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.hostname == worker1
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M
  scheduler:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/scheduler:latest
    networks:
     - net
    secrets:
     -
      source: scheduler.env
      target: /code/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-staging-log-group
        awslogs-region: ap-south-1
        awslogs-stream: scheduler
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      resources:
        reservations:
          cpus: '0.2'
          memory: 124M
        limits:
          cpus: '0.4'
          memory: 256M
networks:
  net:
    driver: overlay
  swarmpit_net:
    external: true
  traefik-public:
    external: true
volumes:
  apperture_redisdata:
    external: true
secrets:
  alertmanager.env:
    external: true
  backend.env:
    external: true
  data_processor1.env:
    external: true
  frontend.env:
    external: true
  scheduler.env:
    external: true
