version: '3.3'
services:
  cdc_consumer:
    image: 212095042672.dkr.ecr.ap-south-1.amazonaws.com/cdc_consumer:latest
    networks:
     - apperture_net
    secrets:
     -
      source: cdc_consumer_10k_earliest_timeout_10M.env
      target: /code/.env
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-prod-events-log-group
        awslogs-region: ap-south-1
        awslogs-stream: cdc_consumer
    deploy:
      placement:
        constraints:
         - node.hostname != jupyter
  connect:
    image: debezium/connect:2.4
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: my_connect_configs
      GROUP_ID: '1'
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KAFKA_HEAP_OPTS: -Xmx2G
    ports:
     - 8083:8083
    networks:
     - apperture_net
    logging:
      driver: awslogs
      options:
        awslogs-group: apperture-prod-events-log-group
        awslogs-region: ap-south-1
        awslogs-stream: connect
    deploy:
      placement:
        constraints:
          - node.hostname == worker4
networks:
  apperture_net:
    external: true
secrets:
  cdc_consumer_10k_earliest_timeout_10M.env:
    external: true
