version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
  events_producer:
    restart: on-failure
    build:
      context: ./events_producer
      target: dev
    ports:
      - "8002:8002"
    volumes:
      - ./events_producer:/code
    depends_on:
      - kafka
  events_consumer:
    restart: on-failure
    build:
      context: ./events_consumer
      target: dev
    volumes:
      - ./events_consumer:/code
    depends_on:
      - kafka
  data_processor:
    build:
      context: ./data_processor
      target: dev
    volumes:
      - ./data_processor:/code
    depends_on:
      - backend
      - redis
  scheduler:
    build:
      context: ./scheduler
      target: dev
    depends_on:
      - backend
      - redis
  db:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=apperture_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    command:
      - '--quiet'
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodata:/data/db
  redis:
    image: 'redis'
    container_name: 'redis'
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data/db'
  clickhouse:
    image: 'clickhouse/clickhouse-server'
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ch_data:/var/lib/clickhouse/
      - ch_logs:/var/log/clickhouse-server/
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes # FIXME: kafka gives warning for this
    volumes:
      - kafka_data:/bitnami/kafka
volumes:
  mongodata: {}
  redisdata: {}
  ch_data: {}
  ch_logs: {}
  kafka_data: {}
