version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
  data_processor:
    build:
      context: ./data_processor
      target: dev
    volumes:
      - ./data_processor:/code
    depends_on:
      - backend
      - redis
  scheduler:
    build:
      context: ./scheduler
      target: dev
    volumes:
      - ./scheduler:/code
    depends_on:
      - backend
      - redis
  db:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=apperture_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    command:
      - '--quiet'
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodata:/data/db
  redis:
    image: 'redis'
    container_name: 'redis'
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data/db'
volumes:
  mongodata: {}
  redisdata: {}
