from datetime import datetime
from unittest.mock import ANY

from models.models import ClickStream, Element, PrecisionEvent


class TestClickStream:
    def setup_method(self):
        self.elements_list = [
            Element(
                tag_name="i",
                attr_class=["ri-route-fill"],
                nth_child=1,
                nth_of_type=1,
                text="",
                attributes={},
            ),
            Element(
                tag_name="button",
                text="",
                attr_class=["chakra-button", "css-vyn3p3"],
                nth_child=1,
                nth_of_type=1,
                attributes={},
            ),
            Element(
                tag_name="div",
                attr_class=["css-1cd4go2"],
                nth_child=1,
                nth_of_type=1,
                attributes={},
            ),
            Element(
                tag_name="div",
                attr_class=["css-0"],
                nth_child=3,
                nth_of_type=3,
                attributes={},
            ),
            Element(
                tag_name="div",
                attr_class=["css-3h169z"],
                nth_child=1,
                nth_of_type=1,
                attributes={},
            ),
            Element(
                tag_name="div",
                attr_class=["css-1xhj18k"],
                nth_child=2,
                nth_of_type=1,
                attributes={},
            ),
            Element(
                tag_name="div",
                attr_id="__next",
                nth_child=1,
                nth_of_type=1,
                attributes={},
            ),
            Element(
                tag_name="body",
                attr_class=["chakra-ui-light"],
                nth_child=2,
                nth_of_type=1,
                attributes={},
            ),
        ]

    def test_build(self):
        """ """

        result = ClickStream.build(
            datasource_id="test_ds_id",
            timestamp=1628607047.37,
            user_id="test_user_id",
            event="$pageview",
            properties={
                "$browser": "Chrome",
                "$browser_language": "en-GB",
                "$browser_version": 109,
                "$ce_version": 0,
                "$current_url": "http://localhost:3000/analytics/app/create",
                "$device_id": "1862a9e52121a37-0b39b9498d8c54-16525635-16a7f0-1862a9e521328fa",
                "$device_type": "Desktop",
                "$elements": [],
                "$event_type": "",
                "$host": "localhost:3000",
                "$insert_id": "uyvllc1rseh4gdym",
                "$lib": "web",
                "$lib_version": "1.43.1",
                "$os": "Mac OS X",
                "$pageview_id": "186348305ce2227-082e406114e4e3-16525635-16a7f0-186348305cf2c5f",
                "$pathname": "/analytics/app/create",
                "$referrer": "http://localhost:3000/analytics/segment/create/638f1aac8e54760eafc64d70",
                "$referring_domain": "localhost:3000",
                "$screen_height": 982,
                "$screen_width": 1512,
                "$session_id": "186348305ca99b-05bdb409c347f-16525635-16a7f0-186348305cb2335",
                "$time": 1675918247.37,
                "$viewport_height": 780,
                "$viewport_width": 1512,
                "$window_id": "186348305cc2af1-0d198248776bf4-16525635-16a7f0-186348305cd2d7c",
                "currency": "",
                "distinct_id": "1862a9e52121a37-0b39b9498d8c54-16525635-16a7f0-1862a9e521328fa",
                "price": 0,
                "token": "63d8ef5a7b02dbd1dcf20dcc",
            },
        )
        assert result == ClickStream(
            "test_ds_id",
            datetime.fromtimestamp(1628607047.37),
            "test_user_id",
            "",
            "$pageview",
            {
                "$browser": "Chrome",
                "$browser_language": "en-GB",
                "$browser_version": 109,
                "$ce_version": 0,
                "$current_url": "http://localhost:3000/analytics/app/create",
                "$device_id": "1862a9e52121a37-0b39b9498d8c54-16525635-16a7f0-1862a9e521328fa",
                "$device_type": "Desktop",
                "$elements": [],
                "$event_type": "",
                "$host": "localhost:3000",
                "$insert_id": "uyvllc1rseh4gdym",
                "$lib": "web",
                "$lib_version": "1.43.1",
                "$os": "Mac OS X",
                "$pageview_id": "186348305ce2227-082e406114e4e3-16525635-16a7f0-186348305cf2c5f",
                "$pathname": "/analytics/app/create",
                "$referrer": "http://localhost:3000/analytics/segment/create/638f1aac8e54760eafc64d70",
                "$referring_domain": "localhost:3000",
                "$screen_height": 982,
                "$screen_width": 1512,
                "$session_id": "186348305ca99b-05bdb409c347f-16525635-16a7f0-186348305cb2335",
                "$time": 1675918247.37,
                "$viewport_height": 780,
                "$viewport_width": 1512,
                "$window_id": "186348305cc2af1-0d198248776bf4-16525635-16a7f0-186348305cd2d7c",
                "currency": "",
                "distinct_id": "1862a9e52121a37-0b39b9498d8c54-16525635-16a7f0-1862a9e521328fa",
                "price": 0,
                "token": "63d8ef5a7b02dbd1dcf20dcc",
            },
        )

    def test_elements_to_string(self):
        result = ClickStream.elements_to_string(self.elements_list)
        assert (
            result
            == 'i.ri-route-fill:nth-child="1"nth-of-type="1";button.chakra-button.css-vyn3p3:nth-child="1"nth-of-type="1";div.css-1cd4go2:nth-child="1"nth-of-type="1";div.css-0:nth-child="3"nth-of-type="3";div.css-3h169z:nth-child="1"nth-of-type="1";div.css-1xhj18k:nth-child="2"nth-of-type="1";div:attr_id="__next"nth-child="1"nth-of-type="1";body.chakra-ui-light:nth-child="2"nth-of-type="1"'
        )

    def test_properties_sanity(self):
        result = ClickStream.build(
            datasource_id="test_ds_id",
            timestamp=1628607047.37,
            user_id="test_user_id",
            event="$autocapture",
            properties={
                "$os": "Android",
                "$browser": "Chrome",
                "$device": "Android",
                "$device_type": "Mobile",
                "$current_url": "https://www.sangeethamobiles.com/checkout-address",
                "$host": "www.sangeethamobiles.com",
                "$pathname": "/checkout-address",
                "$browser_version": 112,
                "$browser_language": "en-US",
                "$screen_height": 851,
                "$screen_width": 393,
                "$viewport_height": 743,
                "$viewport_width": 393,
                "$lib": "web",
                "$lib_version": "1.50.4",
                "$insert_id": "f4u1110ohe7amjwx",
                "$time": 1628607047.37,
                "distinct_id": 67243851,
                "$device_id": "187ae28d8144e-053eeb1665944d-452d356e-51a6b-187ae28d815bc",
                "$search_engine": "google",
                "utm_source": "google",
                "utm_campaign": "Apple-PerformanceMax-Profit",
                "gclid": "Cj0KCQjw6cKiBhD5ARIsAKXUdyalj0I_t7Grq_OhBXyt_EBO6RMyzh05LrklYK5wsSMdkYaaNeZBDQsaAt3XEALw_wcB",
                "$referrer": "https://www.google.com/",
                "$referring_domain": "www.google.com",
                "$user_id": 67243851,
                "$event_type": "click",
                "$ce_version": 1,
                "$elements": [
                    {
                        "tag_name": "a",
                        "$el_text": "Continue",
                        "classes": ["btn", "btn-dark-custom", "btn-place-order"],
                        "attr__state": "[object Object]",
                        "attr__class": "btn btn-dark-custom btn-place-order",
                        "attr__href": "/checkout-payment",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "div",
                        "classes": ["sticky-price__wrap", "w-100"],
                        "attr__class": "sticky-price__wrap w-100",
                        "nth_child": 1,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "section",
                        "classes": ["sticky-menus", "filter-sticky-menus"],
                        "attr__class": "sticky-menus filter-sticky-menus",
                        "nth_child": 3,
                        "nth_of_type": 1,
                    },
                    {"tag_name": "div", "nth_child": 2, "nth_of_type": 1},
                    {
                        "tag_name": "div",
                        "classes": ["mobile", "page-wapper"],
                        "attr__class": "mobile page-wapper",
                        "attr__id": "total-page-wapper",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "div",
                        "attr__id": "__next",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {"tag_name": "body", "nth_child": 2, "nth_of_type": 1},
                ],
                "token": "63ea316c8eed612dec6641d4",
                "$session_id": "187dcd8381a1e4-0487ece0630e9d-b457652-51a6b-187dcd8381b18b",
                "$window_id": "187dcda61ed1a3-0515b94588518-b457652-51a6b-187dcda61ee17f",
                "$pageview_id": "187dcda9cf88-0612db29573448-b457652-51a6b-187dcda9cf9c7",
            },
        )

        assert result == ClickStream(
            "test_ds_id",
            datetime.fromtimestamp(1628607047.37),
            "test_user_id",
            ANY,
            "$autocapture",
            {
                "$os": "Android",
                "$browser": "Chrome",
                "$device": "Android",
                "$device_type": "Mobile",
                "$current_url": "https://www.sangeethamobiles.com/checkout-address",
                "$host": "www.sangeethamobiles.com",
                "$pathname": "/checkout-address",
                "$browser_version": 112,
                "$browser_language": "en-US",
                "$screen_height": 851,
                "$screen_width": 393,
                "$viewport_height": 743,
                "$viewport_width": 393,
                "$lib": "web",
                "$lib_version": "1.50.4",
                "$insert_id": "f4u1110ohe7amjwx",
                "$time": 1628607047.37,
                "distinct_id": 67243851,
                "$device_id": "187ae28d8144e-053eeb1665944d-452d356e-51a6b-187ae28d815bc",
                "$search_engine": "google",
                "utm_source": "google",
                "utm_campaign": "Apple-PerformanceMax-Profit",
                "gclid": "Cj0KCQjw6cKiBhD5ARIsAKXUdyalj0I_t7Grq_OhBXyt_EBO6RMyzh05LrklYK5wsSMdkYaaNeZBDQsaAt3XEALw_wcB",
                "$referrer": "https://www.google.com/",
                "$referring_domain": "www.google.com",
                "$user_id": 67243851,
                "$event_type": "click",
                "$ce_version": 1,
                "$elements": [
                    {
                        "tag_name": "a",
                        "$el_text": "Continue",
                        "classes": ["btn", "btn-dark-custom", "btn-place-order"],
                        "attr__state": "object Object",
                        "attr__class": "btn btn-dark-custom btn-place-order",
                        "attr__href": "/checkout-payment",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "div",
                        "classes": ["sticky-price__wrap", "w-100"],
                        "attr__class": "sticky-price__wrap w-100",
                        "nth_child": 1,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "section",
                        "classes": ["sticky-menus", "filter-sticky-menus"],
                        "attr__class": "sticky-menus filter-sticky-menus",
                        "nth_child": 3,
                        "nth_of_type": 1,
                    },
                    {"tag_name": "div", "nth_child": 2, "nth_of_type": 1},
                    {
                        "tag_name": "div",
                        "classes": ["mobile", "page-wapper"],
                        "attr__class": "mobile page-wapper",
                        "attr__id": "total-page-wapper",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {
                        "tag_name": "div",
                        "attr__id": "__next",
                        "nth_child": 2,
                        "nth_of_type": 1,
                    },
                    {"tag_name": "body", "nth_child": 2, "nth_of_type": 1},
                ],
                "token": "63ea316c8eed612dec6641d4",
                "$session_id": "187dcd8381a1e4-0487ece0630e9d-b457652-51a6b-187dcd8381b18b",
                "$window_id": "187dcda61ed1a3-0515b94588518-b457652-51a6b-187dcda61ee17f",
                "$pageview_id": "187dcda9cf88-0612db29573448-b457652-51a6b-187dcda9cf9c7",
            },
        )
