export const connections = [
  {
    server: 'ClickHouse',
    connection_data: [
      {
        provider: 'mixpanel',
        connection_source: [
          {
            name: '1202978',
            fields: [
              'event_name',
              'user_id',
              'properties.event',
              'properties.properties.$ae_first_app_open_date',
              'properties.properties.$ae_session_length',
              'properties.properties.$ae_updated_version',
              'properties.properties.$app_build_number',
              'properties.properties.$app_release',
              'properties.properties.$app_version',
              'properties.properties.$app_version_string',
              'properties.properties.$bluetooth_enabled',
              'properties.properties.$bluetooth_version',
              'properties.properties.$brand',
              'properties.properties.$carrier',
              'properties.properties.$city',
              'properties.properties.$device_id',
              'properties.properties.$distinct_id_before_identity',
              'properties.properties.$google_play_services',
              'properties.properties.$had_persisted_distinct_id',
              'properties.properties.$has_nfc',
              'properties.properties.$has_telephone',
              'properties.properties.$insert_id',
              'properties.properties.$lib_version',
              'properties.properties.$manufacturer',
              'properties.properties.$model',
              'properties.properties.$mp_api_timestamp_ms',
              'properties.properties.$os',
              'properties.properties.$os_version',
              'properties.properties.$radio',
              'properties.properties.$region',
              'properties.properties.$screen_dpi',
              'properties.properties.$screen_height',
              'properties.properties.$screen_width',
              'properties.properties.$user_id',
              'properties.properties.$wifi',
              'properties.properties.AMOUNT',
              'properties.properties.AppOpen',
              'properties.properties.CHAPTER_ID',
              'properties.properties.CHAPTER_NAME',
              'properties.properties.Is_Basic_Integrity',
              'properties.properties.Is_CTS_Profile_Match',
              'properties.properties.Mmeter_Reading_2',
              'properties.properties.Mmeter_Reading_4',
              'properties.properties.PACKAGE_ID',
              'properties.properties.PACKAGE_NAME',
              'properties.properties.Proximity',
              'properties.properties.String',
              'properties.properties.TIME_TAKEN_IN_VIDEO_PLAY',
              'properties.properties.VIDEO_DURATION',
              'properties.properties.VIDEO_ID',
              'properties.properties.VIDEO_NAME',
              'properties.properties.VIDEO_PLAYED_PERCENTAGE',
              'properties.properties.WATCH_DURATION',
              'properties.properties.amount',
              'properties.properties.article_link',
              'properties.properties.article_name',
              'properties.properties.campaign_id',
              'properties.properties.chapter_id',
              'properties.properties.chapter_name',
              'properties.properties.comment',
              'properties.properties.distinct_id',
              'properties.properties.login_method',
              'properties.properties.mp_country_code',
              'properties.properties.mp_lib',
              'properties.properties.mp_processing_time_ms',
              'properties.properties.new_lang',
              'properties.properties.new_speed',
              'properties.properties.package_id',
              'properties.properties.package_name',
              'properties.properties.path',
              'properties.properties.pre_lang',
              'properties.properties.pre_speed',
              'properties.properties.referrer',
              'properties.properties.result_string',
              'properties.properties.search_string',
              'properties.properties.time',
              'properties.properties.topic_id',
              'properties.properties.topic_name',
              'properties.properties.type',
              'properties.properties.uid',
              'properties.properties.user_type',
              'properties.properties.utm_medium',
              'properties.properties.utm_source',
              'properties.properties.video_name',
              'properties.properties.vp_exam',
              'properties.properties.vp_use',
              'properties.properties.vp_year',
            ],
            datasource_id: '643e4d1e2f9f40f0e001c9e0',
            table_name: 'events',
            database_name: 'default',
          },
        ],
      },
      {
        provider: 'apperture',
        connection_source: [
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51877d031e71ba29898c6',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51889d031e71ba29898c8',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51889d031e71ba29898c8',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51889d031e71ba29898c8',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51889d031e71ba29898c8',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: 'apperture',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b51889d031e71ba29898c8',
            table_name: 'events',
            database_name: 'default',
          },
        ],
      },
      {
        provider: 'amplitude',
        connection_source: [
          {
            name: '1202978',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b518f8276b1834a54c3e36',
            table_name: 'events',
            database_name: 'default',
          },
          {
            name: '28180',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b5193a276b1834a54c3eb0',
            table_name: 'events',
            database_name: 'default',
          },
        ],
      },
      {
        provider: 'mysql',
        connection_source: [
          {
            name: 'mysql',
            fields: ['event_name', 'user_id'],
            datasource_id: '64b52a066b4cae7140c2147e',
            table_name: 'events',
            database_name: 'default',
          },
        ],
      },
    ],
  },
];
