WIOM_CDC_TABLES_WITH_ADDED_TIME_COLUMN = [
    "t_wiom_lead",
    "t_wg_customer",
    "t_store",
    "t_account_messages",
    "t_account",
    "t_firmware",
    "t_rating",
    "t_wani_app_logs",
    "t_wg_customer_audit",
    "t_mandate_info",
    "t_app_device",
    "t_address",
    "t_ticket_comments",
    "t_plan_configuration",
    "t_inventory_request",
    "t_admin",
    "t_revenue",
    "t_admin_mapping",
    "t_user",
    "t_account_mapping1",
    "t_account_balance_sheet",
    "t_process_tracker",
    "t_inventory_audit",
    "t_customer_ticket",
    "t_inventory",
    "t_store_group",
]

DEFAULT_START_DATE_FOR_CDC_TABLES = "2023-01-01"
