WIOM_CDC_TABLES_WITH_TIME_COLUMN = {
    "t_wiom_lead": "modified_time",
    "t_wg_customer": "added_time",
    "t_store": "added_time",
    "t_account_messages": "added_time",
    "t_account": "added_time",
    "t_firmware": "added_time",
    "t_rating": "added_time",
    "t_wani_app_logs": "added_time",
    "t_wg_customer_audit": "modified_time",
    "t_mandate_info": "last_updated_time",
    "t_app_device": "added_time",
    "t_address": "added_time",
    "t_ticket_comments": "added_time",
    "t_plan_configuration": "added_time",
    "t_inventory_request": "added_time",
    "t_admin": "last_login_time",
    "t_revenue": "added_time",
    "t_admin_mapping": "added_time",
    "t_user": "modified_time",
    "t_account_mapping1": "added_time",
    "t_account_balance_sheet": "added_time",
    "t_process_tracker": "added_time",
    "t_inventory_audit": "added_time",
    "t_customer_ticket": "modified_time",
    "t_inventory": "modified_time",
    "t_store_group": "added_time",
    "lead_allocation": "modified_at",
    "t_router_user_mapping": "created_on",
    "t_router_bandwidth": "timestamp",
    "t_wiom_lead_installation": "created_at",
    "t_customer_ticket_audit": "modified_time",
    "t_wiom_lead_audit": "modified_time",
    "booking_logs": "added_time",
    "task_logs": "added_time",
    "t_controller": "last_ping_time",
}


DEFAULT_START_DATE_FOR_CDC_TABLES = "2023-01-01"
