MSSQL_CLICKHOUSE_DATATYPE_MAPPING = {
    "bigint": "Int64",
    "numeric": "Decimal64",
    "bit": "UInt8",
    "smallint": "Int16",
    "decimal": "Decimal64",
    "smallmoney": "Decimal32",
    "int": "Int32",
    "tinyint": "UInt8",
    "money": "Decimal64",
    "float": "Float64",
    "real": "Float32",
    # temporary fix for datetime columns
    "date": "Int64",
    "datetimeoffset": "Int64",
    "datetime2": "Int64",
    "smalldatetime": "Int64",
    "datetime": "Int64",
    "time": "Int64",
    "char": "String",
    "varchar": "String",
    "text": "String",
    "nchar": "String",
    "nvarchar": "String",
    "ntext": "String",
    "binary": "String",
    "varbinary": "String",
    "image": "String",
}
