PSQL_CLICKHOUSE_DATATYPE_MAPPING = {
    "bool": "Bool",
    "bit": "Bool",
    "smallint": "Int16",
    "smallserial": "Int16",
    "integer": "Int32",
    "serial": "Int32",
    "bigint": "Int64",
    "bigserial": "Int64",
    "oid": "Int64",
    "real": "Float32",
    "double precision": "Float64",
    "char": "String",
    "varchar": "String",
    "character": "String",
    "character varying": "String",
    "timestamptz": "String",
    "timetz": "String",
    "interval": "Int64",
    "bytea": "String",
    "json": "String",
    "jsonb": "String",
    "xml": "String",
    "uuid": "String",
    "ltree": "String",
    "citext": "String",
    "inet": "String",
    "int4range": "String",
    "int8range": "String",
    "numrange": "String",
    "tsrange": "String",
    "tstzrange": "String",
    "daterange": "String",
    "enum": "String",
    "date": "Int64",
    "time": "Int64",
    "timestamp": "Int64",
    "numeric": "Decimal64",
    "decimal": "Decimal64",
    "money": "Decimal64",
}
