name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            data_processor:
              - 'data_processor/**'
            scheduler:
              - 'scheduler/**'
            alertmanager:
              - 'alertmanager/**'
            events_producer:
              - 'events_producer/**'
            events_consumer:
              - 'events_consumer/**'
            airflow:
              - 'airflow/**'
            cdc_consumer:
              - 'cdc_consumer/**'
            event_logs_producer:
              - 'event_logs_producer/**'
            event_logs_consumer:
              - 'event_logs_consumer/**'
            events_config_consumer:
              - 'events_config_consumer/**'
            event_service_bus_consumer_producer:
              - 'event_service_bus_consumer_producer/**'

      - name: Set short commit-sha
        id: commit
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        if: steps.filter.outputs.backend == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: latest
        run: |
          cd backend
          mv .defaults .env
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Frontend
        if: steps.filter.outputs.frontend == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: latest
        run: |
          cd frontend
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Data Processor
        if: steps.filter.outputs.data_processor == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: data_processor
          IMAGE_TAG: latest
        run: |
          cd data_processor
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Scheduler
        if: steps.filter.outputs.scheduler == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: scheduler
          IMAGE_TAG: latest
        run: |
          cd scheduler
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push AlertManager
        if: steps.filter.outputs.alertmanager == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: alertmanager
          IMAGE_TAG: latest
        run: |
          cd alertmanager
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push Events Producer
        if: steps.filter.outputs.events_producer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: events_producer
          IMAGE_TAG: latest
        run: |
          cd events_producer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Events Consumer
        if: steps.filter.outputs.events_consumer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: events_consumer
          IMAGE_TAG: latest
        run: |
          cd events_consumer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push CDC Consumer
        if: steps.filter.outputs.cdc_consumer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cdc_consumer
          IMAGE_TAG: latest
        run: |
          cd cdc_consumer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push Airflow
        if: steps.filter.outputs.airflow == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: airflow
          IMAGE_TAG: latest
        run: |
          cd airflow
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push Event Logs Producer
        if: steps.filter.outputs.event_logs_producer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: event_logs_producer
          IMAGE_TAG: latest
        run: |
          cd event_logs_producer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Event Logs Consumer
        if: steps.filter.outputs.event_logs_consumer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: event_logs_consumer
          IMAGE_TAG: latest
        run: |
          cd event_logs_consumer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push Event Config Consumer
        if: steps.filter.outputs.events_config_consumer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: events_config_consumer
          IMAGE_TAG: latest
        run: |
          cd events_config_consumer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

      - name: Build and Push Event Service Bus Consumer
        if: steps.filter.outputs.event_service_bus_consumer_producer == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: event_service_bus_consumer_producer
          IMAGE_TAG: latest
        run: |
          cd event_service_bus_consumer_producer
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
