name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            data_processor:
              - 'data_processor/**'
            scheduler:
              - 'scheduler/**'
            alertmanager:
              - 'alertmanager/**'

      - name: Set short commit-sha
        id: commit
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        if: steps.filter.outputs.backend == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: latest
        run: |
          cd backend
          mv .defaults .env
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Frontend
        if: steps.filter.outputs.frontend == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: latest
        run: |
          cd frontend
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Data Processor
        if: steps.filter.outputs.data_processor == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: data_processor
          IMAGE_TAG: latest
        run: |
          cd data_processor
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push Scheduler
        if: steps.filter.outputs.scheduler == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: scheduler
          IMAGE_TAG: latest
        run: |
          cd scheduler
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
      
      - name: Build and Push AlertManager
        if: steps.filter.outputs.alertmanager == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: alertmanager
          IMAGE_TAG: latest
        run: |
          cd alertmanager
          docker build --target production -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.commit.outputs.sha_short }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
