name: Pull Request Test automation

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Filter changes from backend
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            data_processor:
              - 'data_processor/**'
            events_consumer:
              - 'events_consumer/**'
            frontend:
              - 'frontend/**'
            airflow:
              - 'airflow/**'
            event_logs_consumer_v2:
              - 'event_logs_consumer_v2/**'
      - name: Testing Backend code
        if: steps.filter.outputs.backend == 'true'
        run: |
          cd backend
          mv .defaults .env
          docker build . --target tests

      - name: Testing Data Processor code
        if: steps.filter.outputs.data_processor == 'true'
        run: |
          cd data_processor
          docker build . --target tests
      
      - name: Testing Events Consumer code
        if: steps.filter.outputs.events_consumer == 'true'
        run: |
          cd events_consumer
          docker build . --target tests

      - name: Testing Frontend code
        if: steps.filter.outputs.frontend == 'true'
        run: |
          cd frontend
          docker build . --target builder

      - name: Testing Airflow code
        if: steps.filter.outputs.airflow == 'true'
        run: |
          cd airflow
          docker build . --target tests
      
      - name: Testing Event Logs Consumer v2 code
        if: steps.filter.outputs.event_logs_consumer_v2 == 'true'
        run: |
          cd event_logs_consumer_v2
          docker build . --target tests
