default_events = [
    "UTM Visited",
    "App Launched",
    "Notification Viewed",
    "App Uninstalled",
    "App Installed",
    "Notification Clicked",
    "Push Impressions",
    "Notification Delivered",
    "Notification Replied",
    "Reply Sent",
    "Identity Set",
    "Identity Error",
    "Identity Reset",
    "Experiment Rendered",
    "App Version Changed",
    "Reachable By",
    "Channel Unsubscribed",
    "Geocluster Entered",
    "Geocluster Exited",
    "AB Experiment Rendered",
    "AB Experiment Rolled Out",
    "AB Experiment Stopped",
    "AB Experiment Disqualified",
    "Push Unregistered",
    "Partner Sync",
    "SCOutgoing",
    "SCIncoming",
    "SCEnd",
    "SCBilled",
    "SCRecordedBilled",
    "Channel Subscribed",
    "Session Concluded",
    "Notification Sent",
    "Charged",
    "App Opened",
    "bottom_nav_dest_opened",
    "Drivers Shown",
    "Got users location",
    "banner_viewed",
    "smart_card_viewed",
    "IMEI permission action",
    "bottom_nav_dest_clicked",
    "Signed In",
    "action_viewed",
    "Booking Card - Clicked",
    "Set Pickup Location",
    "First Review started",
    "First Review complete",
    "Request Driver",
    "Vertical Icon Clicked",
    "Wash - Home Viewed",
    "Wash - Exit",
    "All Services - Clicked",
    "All Services - Viewed",
    "Menu Item Clicked",
    "Location search result selected",
    "Opened - FASTag Recharge",
    "Redeem Coins - Screen Viewed",
    "Closed - Coins",
    "Redeem Coins - Card Viewed",
    "Pitstop - Screen Viewed",
    "Pitstop - Screen Closed",
    "insurance_homepage_opened",
    "insurance_car_dub_submitted",
    "Wash - Details Screen",
    "Wash - Buy Now",
    "Wash - Time Slot Screen",
    "Wash - Payment Started",
    "Pitstop - Car Changed",
    "Wash - Waterless Viewed",
    "Opened - Coins",
    "Opened - RSA",
    "Closed - RSA",
    "Redeem Coins - Swiped",
    "Redeem Coins - Redeemed",
    "Home - Banner Clicked",
    "insurance_icon_clicked",
    "Closed - FASTag Recharge",
    "Home Screen - Viewed",
    "Pitstop - Item Viewed",
    "Pitstop - Book Details Filled",
    "Pitstop - View Item Closed",
    "DU Secure event",
    "Booking Created",
    "Booking details viewed",
    "Service Rating - Shown",
    "Service Rating - Rated",
    "Service Rating - Submitted",
    "test",
    "Pitstop - Checkout Success",
    "Pitstop - Preffered Date Filled",
    "Black - Renew Banner",
    "Black - Home Page",
    "Payments Screen - Viewed",
    "Black Landing - Viewed",
    "Promo Applied",
    "smart_card_clicked",
    "insurance_view_plans_clicked",
    "insurance_quotes_screen_loading_started",
    "insurance_plan_detail_clicked",
    "insurance_plan_choices_submitted",
    "insurance_quotes_screen_loading_finished",
    "ckyc_failed",
    "Black - Renew Action",
    "insurance_details_car_owners_submitted",
    "DU Secure Updated",
    "Estimated usage changed",
    "Black - Checkout Started",
    "Refer Code Copied",
    "Car type changed",
    "Refer Button Clicked",
    "Booking cancelled",
    "Service Rating - Interacted",
    "Booking Updated",
    "Pitstop - Explore Services Clicked",
    "idv_modified",
    "ckyc_success",
    "insurance_details_vehicle_submitted",
    "Force Update Action (Android)",
    "Assigned Driver",
    "Driver On Way",
    "Driver Reached",
    "Started drive",
    "Created Booking",
    "Confirm Booking",
    "Ended drive",
    "Autodispatch started",
    "Completed Booking",
    "pn_to_pl",
    "Purchased DUBlack",
    "Signed up",
    "Wash Completed",
    "Cashback Added",
    "Scratch card - Received",
    "action_clicked",
    "Pitstop - Doorstep Selected",
    "Pay from summary screen",
    "add_on_applied",
    "Wash - Order Placed Screen",
    "Promo Application",
    "Payments - Add Money",
    "Black - Checkout Completed",
    "Location search clicked",
    "Set Location Map Shown",
    "Choose on map clicked",
    "Payments - Linked Method",
    "Selected Payment Option",
    "User Car Details Entered",
    "Payment mode changed during trip",
    "Button clicked",
    "Payment pending",
    "Quick Action Clicked",
    "insurance_details_previous_policy_submitted",
    "insurance_details_communication_submitted",
    "insurance_review_buy_opened",
    "Rejected Booking",
    "Pitstop - Promo Code",
    "insurance_review_buy_modified",
    "insurance_buy_now_clicked",
    "insurance_price_breakup_clicked",
]
